### PR TITLE
Comparison and logical operators

### PR DESCRIPTION
**Pull request by nokome**
Add comparison operators (e.g. `<`, `>=`) and logical operators (e.g. `and`, `or`)

### CODE REVIEW

**Comment by oliver----** [comment]
Yay! Welcome to mini :)

**Comment by oliver----** [comment]
Great! Looking good. You want me to merge?

**Comment by nokome** [comment]
Hey! Yeah, was having some coding withdrawal symptoms - haven't done any for at least a week :) So thought I would have a go at fixing some issues that have come up during demos (logical operators are useful for test cells!). Just finishing off this PR with unary operators - will ping you when I'm done.

**Comment by oliver----** [comment]
Cool. Seems you found your way around here already.  🥇

**Comment by nokome** [comment]
@oliver---- : I feel that we should test the integration of this PR with `MiniContext` before merging. Needs new methods e.g `gte`, `neg` implemented there. There is no real hurry to merge this. Feel free to fix naming, if you don't like what I have used. Good night :zzz:

**Comment by oliver----** [comment]
Alright.
Have a nice sleep!

**Comment by nokome** [comment]
Some further thoughts. This PR adds two logical operators `or` and `and` which differ from the other operators in that they are words. Perhaps instead we should take a general approach of making all operators non-word characters, and reserving words for variables or function names. So `and` should be `&&` and `or` should be `||`.

Furthermore, most operators, with the possible exception of the forward pipe `|`, should simply be more readable "shortcuts" to function calls. For example, in Mini the following expressions would be equivalent:
```
a + b > 10 && c==1
```
```
and(add(a, b) > 10, c==1)
```
```
 and(greater_than(add(a, b), 10), equal(c, 1))
```
Having functions which map to each operator (e.g. `&&`: `and`, `==`: `equal`) emphasises the functional nature of Mini and also means that we keep the implementations, including multiple-type-based-dispatch in one place - in libcore. e.g. the `equal` function is already implemented here: https://github.com/stencila/libcore/blob/master/js/src/equal.js

Thoughts?

**Comment by oliver----** [comment]
Sounds reasonable!

**Comment by nokome** [comment]
OK, thanks. I'm merging this now and will create a new PR for the "operators as function calls approach"

**Pull request merged**
